### ISSUE TITLE
Stacktrace when quitting.

### ISSUE THREAD

**Issue by dsully** [gorbit99/codewindow.nvim#22] opened 2022-10-21 15:23 UTC
```
Error executing vim.schedule lua callback: .../pack/packer/opt/codewindow.nvim/lua/codewindow/text.lua:87: Failed to delete line
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	.../pack/packer/opt/codewindow.nvim/lua/codewindow/text.lua:87: in function 'update_minimap'
	...ack/packer/opt/codewindow.nvim/lua/codewindow/window.lua:95: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>⏎
```

This happens when opening any file, and then quitting Neovim.

**Comment by gorbit99** [comment] 2022-10-22 05:22
I can't reproduce this with the latest version. What config are you using and what file are you opening?

**Comment by dsully** [comment] 2022-10-22 14:25
Latest version, any file / file type. My config:

```language:lua
local minimap = require("codewindow")

minimap.setup({
    auto_enable = true,
    exclude_filetypes = require("tables.types").ignored_file_types,
    max_lines = 65536,
})

minimap.apply_default_keybinds()
```

**Comment by gorbit99** [comment] 2022-10-22 21:28
Odd, I can't reproduce it at all even with that config, are you sure there isn't a different plugin or setup that doesn't play nice with codewindow? Might also be a platform difference.

**Comment by dsully** [comment] 2022-10-23 17:29
I'm not sure.. would have to do a pretty large process of elimination to tell.

Platform-wise - same error on both Linux and macOS, running Neovim 0.8

**Comment by gorbit99** [comment] 2022-10-23 17:52
Probably something specific to your setup then, some other plugin not playing nice with codewindow. Not even rolling back to 0.8 could make me encounter this. I'll close this, feel free to reopen it if you can pinpoint what could be causing this.

**Comment by dsully** [comment] 2022-10-23 18:23
Narrowing it down now.. appears to be something with `null-ls`.

**Comment by gorbit99** [comment] 2022-10-23 18:27
Hmm, what's your null-ls config like?

**Comment by dsully** [comment] 2022-10-23 18:51
https://github.com/dsully/dotfiles/blob/master/.config/nvim/lua/config/lsp/servers/null.lua

**Comment by dsully** [comment] 2022-10-23 19:31
FYI, the relevant code from https://github.com/neovim/neovim/blob/master/src/nvim/api/buffer.c#L429

```language:c
// If the size of the range is reducing (ie, new_len < old_len) we
  // need to delete some old_len. We do this at the start, by
  // repeatedly deleting line "start".
  size_t to_delete = (new_len < old_len) ? (size_t)(old_len - new_len) : 0;
  for (size_t i = 0; i < to_delete; i++) {
    if (ml_delete((linenr_T)start, false) == FAIL) {
      api_set_error(err, kErrorTypeException, "Failed to delete line");
      goto end;
    }
  }
```

**Comment by gorbit99** [comment] 2022-10-23 19:44
Nice, with your config, I can reproduce it, let me get to it

**Comment by gorbit99** [comment] 2022-10-23 19:48
Check if it works now with the latest commit

**Closed** 2022-10-23 19:47 UTC

**Comment by dsully** [comment] 2022-10-23 20:40
That appears to have fixed it. Thanks!
